plugin: netbox.netbox.nb_inventory

# Netbox connection settings
api_endpoint: http://192.168.0.202:8000
token: ZLKOcPPuor3eUrZtILD87OF1jAWIDuVkdNl2dbLn
validate_certs: false

# Group devices automatically by these attributes
group_by:
  - device_roles  # Creates groups like: device_roles_router    
  - platforms     # Creates groups like: platforms_cisco_ios
  - sites         # Creates groups like: sites_main_dc
  - tags          # Creates groups based on device tags

query_filters:
  - status: active

# Map NetBox fields to Ansible variables
compose:
  # Extract IP without subnet mask (192.168.1.101/24 -> 192.168.1.101)
  ansible_host: primary_ip4.address | split('/') | first
  # Use platform slug for network_os
  # ansible_network_os: platform.slug
  ansible_network_os: platform.name | regex_replace('.*IOS.*', 'cisco.ios.ios', ignorecase=True) | default('unknown')

# Only include devices that have a primary IP assigned
device_query_filters:
  - has_primary_ip: true